"""Git-backed notebook history.

Each user's notebook directory is initialised as a private git repository.
Every save lands as a commit, so the UI can show a real timeline and let
the user restore any earlier version without a separate database.

Design choices:
* One repo per user — matches the existing per-user namespacing in
  :func:`rednotebook.server.dependencies.notebook_storage_dep` and keeps
  one user's history out of another's.
* No remotes by default. Git provides local versioning here, not
  collaboration. A future Phase-4 feature can add an opt-in remote.
* Failures are non-blocking. If git isn't installed, the working tree
  is dirty in a weird way, or the repo init fails for any reason, the
  save path still succeeds — history just stops accumulating. The
  caller logs the warning so the regression is visible in server logs.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from pathlib import Path

_log = logging.getLogger(__name__)


@dataclass(frozen=True)
class CommitInfo:
    """A single commit affecting a tracked notebook file."""

    sha: str
    short_sha: str
    timestamp: float
    iso_timestamp: str
    author_name: str
    author_email: str
    message: str


class NotebookGitStore:
    """Tiny wrapper over a per-user git repo.

    All paths passed in are absolute. The repo lives at ``base_dir/.git``.
    Methods that read history return empty lists / None when the file
    has never been committed, never raise on cold start.
    """

    def __init__(self, base_dir: str | Path) -> None:
        self.base_dir = Path(base_dir).resolve()

    # ----- Lazy init --------------------------------------------------------
    def _ensure_repo(self):  # type: ignore[no-untyped-def]
        try:
            from git import Repo  # type: ignore[import-not-found]
        except ImportError:
            return None
        self.base_dir.mkdir(parents=True, exist_ok=True)
        try:
            return Repo(self.base_dir)
        except Exception:
            # git.exc.InvalidGitRepositoryError or NoSuchPathError — both
            # mean "need to init".
            pass
        try:
            repo = Repo.init(self.base_dir, initial_branch="main")
            # Local-only identity. Avoids surfacing the user's global
            # git config or failing on machines where neither is set.
            with repo.config_writer() as cfg:
                cfg.set_value("user", "name", "rednotebook")
                cfg.set_value("user", "email", "notebooks@rednotebook.local")
                cfg.set_value("commit", "gpgsign", "false")
            # Drop a .gitignore so transient artifacts don't show up in
            # diffs. Everything else is fair game — saves are exactly
            # the JSON we want to track.
            gi = self.base_dir / ".gitignore"
            if not gi.exists():
                gi.write_text(
                    "# Auto-generated by rednotebook\n"
                    ".DS_Store\n"
                    "Thumbs.db\n"
                    "*.tmp\n",
                    encoding="utf-8",
                )
            return repo
        except Exception as exc:
            _log.warning(
                "Could not initialise notebook git repo at %s: %s",
                self.base_dir,
                exc,
            )
            return None

    # ----- Mutations --------------------------------------------------------
    def commit(
        self,
        file_path: str | Path,
        message: str,
        *,
        author_name: str | None = None,
        author_email: str | None = None,
    ) -> str | None:
        """Stage and commit ``file_path``. Returns the new commit sha or None.

        ``None`` means either the repo couldn't be opened, the file isn't
        inside ``base_dir`` (defensive — we never want to chase symlinks
        elsewhere), or the working tree had no change vs. HEAD.
        """
        repo = self._ensure_repo()
        if repo is None:
            return None
        try:
            from git import Actor  # type: ignore[import-not-found]
        except ImportError:  # pragma: no cover - guarded above
            return None

        abs_path = Path(file_path).resolve()
        try:
            rel = abs_path.relative_to(self.base_dir)
        except ValueError:
            _log.warning(
                "Refusing to commit %s — outside notebook dir %s",
                abs_path,
                self.base_dir,
            )
            return None

        try:
            repo.index.add([os.fspath(rel)])
            # Don't create empty commits when the user "saved" without
            # changes. git diffs against HEAD via status entries.
            staged = repo.index.diff("HEAD") if repo.head.is_valid() else None
            if repo.head.is_valid() and not staged:
                return None
            author = Actor(
                author_name or "rednotebook",
                author_email or "notebooks@rednotebook.local",
            )
            commit = repo.index.commit(
                message, author=author, committer=author, skip_hooks=True
            )
            return commit.hexsha
        except Exception as exc:
            _log.warning(
                "git commit failed for %s (%s): %s", abs_path, self.base_dir, exc
            )
            return None

    def restore(
        self,
        file_path: str | Path,
        sha: str,
        *,
        author_name: str | None = None,
        author_email: str | None = None,
        message: str | None = None,
    ) -> str | None:
        """Restore ``file_path`` to the version at ``sha`` and commit the change.

        Returns the new commit sha (of the restore commit) on success.
        """
        repo = self._ensure_repo()
        if repo is None:
            return None
        abs_path = Path(file_path).resolve()
        try:
            rel = abs_path.relative_to(self.base_dir)
        except ValueError:
            return None
        try:
            content = repo.git.show(f"{sha}:{rel.as_posix()}")
        except Exception as exc:
            _log.warning("git show %s:%s failed: %s", sha, rel, exc)
            return None
        abs_path.write_text(content, encoding="utf-8")
        commit_msg = message or f"restore notebook to {sha[:7]}"
        return self.commit(
            abs_path,
            commit_msg,
            author_name=author_name,
            author_email=author_email,
        )

    # ----- Reads ------------------------------------------------------------
    def history(
        self,
        file_path: str | Path,
        *,
        limit: int = 50,
    ) -> list[CommitInfo]:
        """Return the most recent commits that touched ``file_path``."""
        repo = self._ensure_repo()
        if repo is None or not repo.head.is_valid():
            return []
        abs_path = Path(file_path).resolve()
        try:
            rel = abs_path.relative_to(self.base_dir)
        except ValueError:
            return []
        try:
            commits = list(
                repo.iter_commits(paths=os.fspath(rel), max_count=max(1, int(limit)))
            )
        except Exception:
            return []
        return [
            CommitInfo(
                sha=c.hexsha,
                short_sha=c.hexsha[:7],
                timestamp=float(c.committed_date),
                iso_timestamp=c.committed_datetime.isoformat(),
                author_name=str(c.author.name or ""),
                author_email=str(c.author.email or ""),
                message=(c.message or "").strip(),
            )
            for c in commits
        ]

    def read_at(
        self,
        file_path: str | Path,
        sha: str,
    ) -> str | None:
        """Return the contents of ``file_path`` at commit ``sha``, or None."""
        repo = self._ensure_repo()
        if repo is None:
            return None
        abs_path = Path(file_path).resolve()
        try:
            rel = abs_path.relative_to(self.base_dir)
        except ValueError:
            return None
        try:
            return repo.git.show(f"{sha}:{rel.as_posix()}")
        except Exception:
            return None
