"""Infographic generator (HTML output)."""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from rednotebook.ai.base import InfographicBrief

_BASE_CSS = """
:root {
  color-scheme: light dark;
  --bg: #0b0d12;
  --surface: #11151c;
  --card: #161b24;
  --muted: #8b95a7;
  --text: #e6ebf2;
  --accent: #ff4d6d;
  --border: #232b39;
}
@media (prefers-color-scheme: light) {
  :root {
    --bg: #f7f8fa;
    --surface: #ffffff;
    --card: #ffffff;
    --muted: #5e6776;
    --text: #0b0d12;
    --accent: #e11d48;
    --border: #e5e7eb;
  }
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto, sans-serif;
  margin: 0;
  background: var(--bg);
  color: var(--text);
  line-height: 1.5;
}
.container { max-width: 1080px; margin: 0 auto; padding: 48px 32px; }
h1 { font-size: 36px; margin: 0 0 8px; letter-spacing: -0.02em; }
h2 { font-size: 22px; margin: 32px 0 16px; }
.subtitle { color: var(--muted); font-size: 16px; }
.metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin: 32px 0; }
.metric {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 20px;
}
.metric .label { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; }
.metric .value { font-size: 28px; font-weight: 600; margin-top: 4px; }
.insights { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 24px; }
.insights ul { padding-left: 20px; margin: 0; }
.insights li { margin: 6px 0; }
.narrative { margin-top: 24px; }
.caveats { color: var(--muted); font-size: 13px; margin-top: 32px; border-top: 1px solid var(--border); padding-top: 16px; }
.footer { color: var(--muted); font-size: 12px; margin-top: 48px; text-align: center; }
.accent { color: var(--accent); }
"""


def render_infographic_html(
    brief: InfographicBrief,
    *,
    template: str = "executive_kpi_brief",
    source_label: str | None = None,
) -> str:
    """Return a complete, standalone HTML infographic document."""
    metrics_html = "".join(
        f'<div class="metric"><div class="label">{html.escape(str(m.get("label", "")))}</div>'
        f'<div class="value">{html.escape(str(m.get("value", "")))}</div></div>'
        for m in brief.key_metrics
    )
    insights_html = "".join(
        f"<li>{html.escape(insight)}</li>" for insight in brief.insights
    )
    caveats_html = "".join(
        f"<li>{html.escape(c)}</li>" for c in brief.caveats
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{html.escape(brief.title)}</title>
<style>{_BASE_CSS}</style>
</head>
<body>
<div class="container">
  <p class="subtitle accent">{html.escape(template.replace('_', ' ').title())}</p>
  <h1>{html.escape(brief.title)}</h1>
  <p class="subtitle">{html.escape(brief.summary)}</p>

  <div class="metrics">{metrics_html}</div>

  <h2>Key insights</h2>
  <div class="insights"><ul>{insights_html}</ul></div>

  {f'<div class="narrative"><h2>Narrative</h2><p>{html.escape(brief.narrative)}</p></div>' if brief.narrative else ''}

  {f'<div class="caveats"><strong>Caveats</strong><ul>{caveats_html}</ul></div>' if caveats_html else ''}

  <div class="footer">
    Generated by RedNotebook AI{f" · Source: {html.escape(source_label)}" if source_label else ""}
  </div>
</div>
</body>
</html>
"""


def export_infographic(
    brief: InfographicBrief,
    path: str | Path,
    *,
    template: str = "executive_kpi_brief",
    source_label: str | None = None,
) -> Path:
    """Write the infographic HTML to disk."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        render_infographic_html(brief, template=template, source_label=source_label),
        encoding="utf-8",
    )
    return target


def brief_to_dict(brief: InfographicBrief) -> dict[str, Any]:
    return brief.model_dump()
